Repository openshift/cluster-kube-storage-version-migrator-operator, pull requests merged in 2021-04, with the labels that each got.

#51 Add IBM cloud managed profile manifest patch
  .gitignore
  Makefile
  go.mod
  go.sum
  manifests/0000_40_kube-storage-version-migrator-operator_07_deployment-ibm-cloud-managed.yaml
  manifests/0000_40_kube-storage-version-migrator-operator_07_deployment.yaml
  profile-patches/ibm-cloud-managed/0000_40_kube-storage-version-migrator-operator_07_deployment.yaml-patch
  vendor/github.com/openshift/build-machinery-go/OWNERS
  vendor/github.com/openshift/build-machinery-go/README.md
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/profile-manifests.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yq.mk
  vendor/modules.txt
Labels: approved, lgtm

#54 Bug 1953539: Set priorityClassName: system-cluster-critical
  bindata/kube-storage-version-migrator/deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#52 Add management workload annotations
  bindata/kube-storage-version-migrator/deployment.yaml
  bindata/kube-storage-version-migrator/namespace.yaml
  manifests/0000_40_kube-storage-version-migrator-operator_02_namespace.yaml
  manifests/0000_40_kube-storage-version-migrator-operator_07_deployment-ibm-cloud-managed.yaml
  manifests/0000_40_kube-storage-version-migrator-operator_07_deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/valid-bug, lgtm
