Repository openshift/cluster-kube-storage-version-migrator-operator, pull requests merged in 2021-05, with the labels that each got.

#56 Bug 1948311: DelegatingAuthenticationOptions TokenReview request timeout
  go.mod
  go.sum
  vendor/k8s.io/apiserver/pkg/authentication/authenticatorfactory/delegating.go
  vendor/k8s.io/apiserver/pkg/server/options/authentication.go
  vendor/k8s.io/apiserver/plugin/pkg/authenticator/token/webhook/webhook.go
  vendor/modules.txt
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#57 bug 1957908: stop reporting empty version
  pkg/operator/targetcontroller/sync.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#58 Bug 1962687: manifests,assets: set runAsUser to not run as root
  bindata/kube-storage-version-migrator/deployment.yaml
  manifests/0000_40_kube-storage-version-migrator-operator_07_deployment-ibm-cloud-managed.yaml
  manifests/0000_40_kube-storage-version-migrator-operator_07_deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
